services:
  api:
    build: ./Contact-banckend
    ports:
      - "4000:4000"
    env_file: .env
    depends_on:
      - db
    networks:
      - app-net

  landing:
    build: ./Contact-frontend
    ports:
      - "3182:80"
    networks:
      - app-net

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3309:3306"
    networks:
      - app-net

volumes:
  db-data:

networks:
  app-net:
    driver: bridge
